package jk509.player;

public interface Constants {
	
	// Things we might want to tweak (for research)
	public static final int MAX_CLUSTER_SIZE = 100;
	public static final int MAX_CLUSTERS = 100;
	
	// Things we might want to tweak (less research-related)
	
	// Things which are probably fixed
	public static final int JAUDIO_FEATURE_COUNT = 138; // #features in default list generated by features.xml
	public static final int FEATURES = 39; // 11 + 13 + 10 + 5 (last 3 are compound feature vectors which get linearised into array)
	public static final String featureXMLLocation = "features.xml";
}
