package jk509.player;

import java.io.Serializable;
import java.util.List;

public class Playlist implements Serializable {

	private static final long serialVersionUID = 516185787632474552L;
	
	// lists of Songs, or lists of IDs?? (the latter currently)

	private String name;
	private List<Integer> list;
	private boolean autoGenerated;

	// Other data...

	public List<Integer> getList() {
		return list;
	}

	public String getName() {
		return name;
	}

	public boolean isAuto() {
		return autoGenerated;
	}
}